<?php

// This file is auto-generated, don't edit it. Thanks.

namespace AntChain\MARKETINGAGENT\Models;

use AlibabaCloud\Tea\Model;

class Task extends Model
{
    // Unique identifier (e.g. UUID) for the task, generated by the server for a new task.
    /**
     * @example 6c7a3d8f9e544c5ab3e17f2a1b9c4e8d
     *
     * @var string
     */
    public $id;

    // The current status of a Task, including state and a message.
    /**
     * @example
     *
     * @var TaskStatus
     */
    public $status;

    // A set of output artifacts for a Task.
    /**
     * @example
     *
     * @var Artifact[]
     */
    public $artifacts;
    protected $_name = [
        'id'        => 'id',
        'status'    => 'status',
        'artifacts' => 'artifacts',
    ];

    public function validate()
    {
        Model::validateRequired('id', $this->id, true);
        Model::validateRequired('status', $this->status, true);
        Model::validateRequired('artifacts', $this->artifacts, true);
    }

    public function toMap()
    {
        $res = [];
        if (null !== $this->id) {
            $res['id'] = $this->id;
        }
        if (null !== $this->status) {
            $res['status'] = null !== $this->status ? $this->status->toMap() : null;
        }
        if (null !== $this->artifacts) {
            $res['artifacts'] = [];
            if (null !== $this->artifacts && \is_array($this->artifacts)) {
                $n = 0;
                foreach ($this->artifacts as $item) {
                    $res['artifacts'][$n++] = null !== $item ? $item->toMap() : $item;
                }
            }
        }

        return $res;
    }

    /**
     * @param array $map
     *
     * @return Task
     */
    public static function fromMap($map = [])
    {
        $model = new self();
        if (isset($map['id'])) {
            $model->id = $map['id'];
        }
        if (isset($map['status'])) {
            $model->status = TaskStatus::fromMap($map['status']);
        }
        if (isset($map['artifacts'])) {
            if (!empty($map['artifacts'])) {
                $model->artifacts = [];
                $n                = 0;
                foreach ($map['artifacts'] as $item) {
                    $model->artifacts[$n++] = null !== $item ? Artifact::fromMap($item) : $item;
                }
            }
        }

        return $model;
    }
}
