// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AntChain.SDK.CREATIVERENDER.Models
{
    // Task is the core unit of action for A2A. It has a current status and when results are created for the task they are stored in the artifact.
    public class Task : TeaModel {
        // Unique identifier (e.g. UUID) for the task, generated by the server for a new task.
        /// <summary>
        /// <b>Example:</b>
        /// <para>6c7a3d8f9e544c5ab3e17f2a1b9c4e8d</para>
        /// </summary>
        [NameInMap("id")]
        [Validation(Required=true)]
        public string Id { get; set; }

        // Unique identifier (e.g. UUID) for the contextual collection of interactions (tasks and messages). Created by the A2A server.
        /// <summary>
        /// <b>Example:</b>
        /// <para>contextid</para>
        /// </summary>
        [NameInMap("context_id")]
        [Validation(Required=false)]
        public string ContextId { get; set; }

        // The current status of a Task, including state and a message.
        [NameInMap("status")]
        [Validation(Required=true)]
        public TaskStatus Status { get; set; }

        // A set of output artifacts for a Task.
        [NameInMap("artifacts")]
        [Validation(Required=true)]
        public List<Artifact> Artifacts { get; set; }

    }

}
