// This file is auto-generated, don't edit it. Thanks.
package com.antgroup.antchain.openapi.marketingagent.models;

import com.aliyun.tea.*;

public class Task extends TeaModel {
    // Unique identifier (e.g. UUID) for the task, generated by the server for a new task.
    /**
     * <strong>example:</strong>
     * <p>6c7a3d8f9e544c5ab3e17f2a1b9c4e8d</p>
     */
    @NameInMap("id")
    @Validation(required = true)
    public String id;

    // The current status of a Task, including state and a message.
    @NameInMap("status")
    @Validation(required = true)
    public TaskStatus status;

    // A set of output artifacts for a Task.
    @NameInMap("artifacts")
    @Validation(required = true)
    public java.util.List<Artifact> artifacts;

    public static Task build(java.util.Map<String, ?> map) throws Exception {
        Task self = new Task();
        return TeaModel.build(map, self);
    }

    public Task setId(String id) {
        this.id = id;
        return this;
    }
    public String getId() {
        return this.id;
    }

    public Task setStatus(TaskStatus status) {
        this.status = status;
        return this;
    }
    public TaskStatus getStatus() {
        return this.status;
    }

    public Task setArtifacts(java.util.List<Artifact> artifacts) {
        this.artifacts = artifacts;
        return this;
    }
    public java.util.List<Artifact> getArtifacts() {
        return this.artifacts;
    }

}
